### ISSUE TITLE
CR2 files should not be treated as tiff files

### ISSUE THREAD

**Issue by darix** [sdsykes/fastimage#104]
see the discussion here https://twitter.com/darixzen/status/1038185056395776003

**Comment by sdsykes** [comment]
It's relatively easy to detect CR2 format, not sure exactly how to find the dimensions of such a file though. Happy to accept a PR for that - alternatively we could just stop CR2 being recognised as TIFF without adding parsing for it.

**Comment by darix** [comment]
On 2018-09-09 13:52, Stephen Sykes wrote:
> It's relatively easy to detect CR2 format, not sure exactly how to
> find the dimensions of such a file though. Happy to accept a PR for
> that - alternatively we could just stop CR2 being recognised as TIFF
> without adding parsing for it.

Just not parsing them at all would be the best probably.

**Comment by darix** [comment]
Any ETA for a new release?

**Comment by sdsykes** [comment]
It's now done. I was just waiting to get travis to pass.

**Comment by darix** [comment]
Thank you

**Comment by darix** [comment]
I think you are missing a tag
