### ISSUE TITLE
Image size is return as nil, nil for raw images!

### ISSUE THREAD

**Issue by sakader** [sdsykes/fastimage#112]
It seems FastImage.size() is not working for uploaded raw files, it's returning nil, nil for size of the raw image? Please find the example below:

FastImage.size("https://mynuphoto-development.s3.amazonaws.com/uploads/images/raw/ef4c2107-a561-462d-bf6d-8d8394865d4d/RAW_SONY_A200.ARW")

**Comment by sdsykes** [comment]
I will investigate. FastImage does not explicitly support raw format files, but on the other hand the format is similar, or based on tiff so it might not be hard to add.

**Comment by sakader** [comment]
Thanks for the quick reply! It will be great if you can add it.

**Comment by sakader** [comment]
Hi @sdsykes, any update adding raw image feature?

**Comment by sdsykes** [comment]
I didn't find any obvious documentation on the web for the format. Some other open source utilities do have parsers, but it's still going to take some time to investigate.

**Comment by sakader** [comment]
Ok, thanks for the update. Will wait to hear from you soon.

**Comment by sakader** [comment]
Any update on the raw image feature?

**Comment by sdsykes** [comment]
Not much. I found documentation here http://lclevy.free.fr/raw/ and a parser here https://github.com/hfiguiere/libopenraw but I don't have much time to work on this. I do accept pull requests though.

**Comment by sdsykes** [comment]
Please provide a pull request for new formats to support, closing this now.
