### ISSUE TITLE
Proposal to remove the "rescue NoMethodError" from some 1.8.7p248 legacy

### ISSUE THREAD

**Issue by Nakilon** [sdsykes/fastimage#121]
I propose to remove the lines: https://github.com/sdsykes/fastimage/blob/c183bb833d812e6a93d52c25e79dd736ebb5b7ad/lib/fastimage.rb#L254-L255
because .gemspec:
```
s.required_ruby_version = '>= 1.9.2'
```
It interferes with something else. For example:
```
Message: <"undefined method `force_encoding' for #<Net::ReadAdapter>">
---Backtrace---
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:438:in `peek'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:511:in `block in parse_type'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:511:in `each'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:511:in `detect'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:511:in `parse_type'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:390:in `parse_size'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:371:in `parse_packets'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/fastimage-2.1.7/lib/fastimage.rb:298:in `block in fetch_using_http_from_parsed_uri'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/webmock-3.11.0/lib/webmock/http_lib_adapters/net_http.rb:177:in `build_net_http_response'
/Users/nakilon/.rbenv/versions/2.3.8/lib/ruby/gems/2.3.0/gems/webmock-3.11.0/lib/webmock/http_lib_adapters/net_http.rb:83:in `request'
```
Didn't resolve this yet, but that exception swallowing seems to get in the way. It throws `FastImage::ImageFetchFailure` instead of `FastImage::UnknownImageType` when I'm webmocking my tests. For example, here the link was html, not image.

UPD: I don't get what the `Net::ReadAdapter` is. The only relevant clue I've found is changelog:

> When making a request with a block that calls #read_body on the request, Net::HTTP causes the body to be set to a Net::ReadAdapter, but WebMock was causing the body to be set to a string.

That probably means that it's FastImage's fault that it treats it as a String.

**Comment by sdsykes** [comment]
Yes I think those lines could be removed.

Not sure what else needs to be changed to fix the issue though.

**Comment by Nakilon** [comment]
I'm still webmocking my tests. Was going to propose the edit against the ReadAdapter exception when I'm done.
But now I'm wondering why it's `>=` here, not `<=` https://github.com/sdsykes/fastimage/blob/c183bb833d812e6a93d52c25e79dd736ebb5b7ad/lib/fastimage.rb#L474

**Comment by Nakilon** [comment]
See https://github.com/sdsykes/fastimage/pull/123
