### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by rsamoilov** [sdsykes/fastimage#128]
Hey there,

Thank you for the great gem!

There are some changes in `master` branch that are not published yet. Those include support for HEIC format.

Are you planning a release some time soon?

**Comment by SamSaffron** [comment]
@sdsykes ping me if you need any help administering the gem Discourse would be happy to take on stuff like pushing a new gem release.

**Comment by sdsykes** [comment]
@SamSaffron you are invited on GitHub, also need to grant you permission on rubygems, I'll look into that.

**Comment by SamSaffron** [comment]
Oh thanks so much, my rubygems emails is `sam.saffron@gmail.com`  `gem owner --add sam.saffron@gmail.com fastimage` should do the trick (feel free to junk this comment)

Promise to use this right very responsibly mainly to save you the hassle of publishing when you are running a bit busy.

**Comment by SamSaffron** [comment]
Thanks so much ... cutting a release now!

**Comment by SamSaffron** [comment]
2.2.4 is now released! :confetti_ball:

**Comment by sdsykes** [comment]
Thanks @SamSaffron !
