### ISSUE TITLE
SVG images with small dimension detected as zero pixels, ignoring units

### ISSUE THREAD

**Issue by mMerlin** [sdsykes/fastimage#129]
[Discourse](https://github.com/discourse/discourse) uses fastimage as an initial check on image sizes. Fastimage detects svg images that have the "height" or "width" attribute value less than "1" as zero pixels. That ignores the units specified with the attribute value. If it was less than "1px", zero could be a reasonable interpretation. However less than "1in" is considerably different. Especially when the "viewBox" value shows that 1 inch is actually 1000 units. The (current) associated [discourse code](https://github.com/discourse/discourse/blob/03fc31e23bf7f7ed78488e700680c4388a7a319e/lib/upload_creator.rb#L189-L202) is quoted here

```ruby
  def extract_image_info!
    @image_info = FastImage.new(@file) rescue nil
    @file.rewind

    if @image_info.nil?That is
      @upload.errors.add(:base, I18n.t("upload.images.size_not_found"))
    elsif max_image_pixels > 0 && pixels >= max_image_pixels * 2
      @upload.errors.add(:base, I18n.t("upload.images.larger_than_x_megapixels", max_image_megapixels: SiteSetting.max_image_megapixels * 2))
    end
  end
```

For the problem images, the size_not_found error is displayed, indicating `pixels == 0`.

Here is a minimal failing example

```xml image1.svg
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg
  xmlns="http://www.w3.org/2000/svg" xmlns:svg="http://www.w3.org/2000/svg"
  width="1.2in" height="0.9in"
  viewBox="0 0 1200 900"
>
  <line x1="1100" x2="100" y1="100" y2="800" stroke="#000000" stroke-width="50"/>
</svg>
```

github does support uploading svg files, so I renamed to append ".txt" to the name.

[image1.svg.txt](https://github.com/sdsykes/fastimage/files/6660177/image1.svg.txt)

Increasing the size and adjusting viewbox to maintain aspect ratio to `height="1in" viewBox="0 0 1200 1000"` works.

[image2.svg.txt](https://github.com/sdsykes/fastimage/files/6660192/image2.svg.txt)

Doubling the height and width to `width="2.4in" height="1.8in"`, then scaling back down in the post works.

[image3.svg.txt](https://github.com/sdsykes/fastimage/files/6660193/image3.svg.txt)

Changing the `0.9in` height to the equivalent `22.86mm` works.

[image4.svg.txt](https://github.com/sdsykes/fastimage/files/6660196/image4.svg.txt)

None of those workarounds are helpful for a typical forum user (https://forum.fritzing.org/). The images are associated with an application, where dimensions have meaning beyond the display size. Typical users works with inkscape, without knowing anything about the raw svg xml. Or the image is out of a part file created by other users or application code. The units are typically inches, because the convention is 0.1 spacing for many things.

**Comment by SamSaffron** [comment]
Looks like we have a fix in Discourse. Not sure if we need to change anything with the gem.

**Comment by mMerlin** [comment]
> Looks like we have a fix in Discourse. Not sure if we need to change anything with the gem.

That would depend on whether anyone else is using fastimage for something similar. The latest information for the [Discourse fix](https://meta.discourse.org/t/svg-images-with-dimension-less-than-1-fail-to-upload/194009) is still tentative.

**Comment by sdsykes** [comment]
Yes, thanks for the detailed description. I do think it would be useful to somehow fix this case in FastImage.
