### ISSUE TITLE
In fastimage >=2.2.2 calling FastImage.size(nil) raises NoMethodError

### ISSUE THREAD

**Issue by Aqualon** [sdsykes/fastimage#138]
We use the MetaInspector gem and it sometimes passes on nil values for url to FastImage.size (see https://github.com/metainspector/metainspector/issues/359).

I found out this started failing with the fastimage 2.2.2 release:
```
> FastImage.size(nil)
/gems/3.0.0/gems/fastimage-2.2.2/lib/fastimage.rb:232:in `initialize': undefined method `start_with?' for nil:NilClass (NoMethodError)
```

`FastImage.size(nil)` in 2.2.1 returns `nil`.

**Comment by Aqualon** [comment]
Seems to be triggered by the removal of `rescue NoMethodError` in https://github.com/sdsykes/fastimage/commit/437318220b847a914661dada71ef34afd905d1d2#diff-e5e6831010e661c7badcc0cf185d519bded3217b55a7c5ff69ae707ec0f596e2L254-L255

**Comment by sdsykes** [comment]
Agree, fastimage should return nil unless raise_on_failure is set.

**Comment by Aqualon** [comment]
Thanks for the fix, can we expect a release with the fix any time soon?
