### ISSUE TITLE
Benchmark in readme 

### ISSUE THREAD

**Issue by toy** [sdsykes/fastimage#151]
I maintain the `image_size` gem and noticed that the benchmark in the readme of `fastimage` uses OpenURI to fetch the complete file to showcase `image_size`. However, few years ago, I added an efficient interface for working with URLs to the gem. The tiff image used in the benchmark in the `fastimage` readme is no longer available, so I had to find another one, but here is the current benchmark (`image_size` is faster with it due to fetching only needed data range).

```ruby
require 'benchmark'
require 'image_size/uri'
require 'fastimage'

uri_jpeg = 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Mardin_1350660_1350692_33_images.jpg'
uri_tiff = 'https://upload.wikimedia.org/wikipedia/commons/1/14/Center-Filled_LIMA.tif'

Benchmark.bm do |x|
  x.report('jpeg/image_size: ') { p ImageSize.url(uri_jpeg).size }
  x.report('jpeg/fastimage: ')  { p FastImage.size(uri_jpeg) }
  x.report('tiff/image_size: ') { p ImageSize.url(uri_tiff).size }
  x.report('tiff/fastimage: ')  { p FastImage.size(uri_tiff) }
end
```
Output:
```
       user     system      total        real
jpeg/image_size: [9545, 6623]
  0.007226   0.002578   0.009804 (  0.149030)
jpeg/fastimage: [9545, 6623]
  0.003590   0.001341   0.004931 (  0.185543)
tiff/image_size: [22841, 19404]
  0.006041   0.001286   0.007327 (  0.195920)
tiff/fastimage: [22841, 19404]
  0.158832   0.124926   0.283758 (  3.152612)
```

**Comment by sdsykes** [comment]
That's pretty nice, ImageSize is way faster at sizing that file. I'll fix the readme.
