### ISSUE TITLE
Infinite loop when passing a Pathname

### ISSUE THREAD

**Issue by nekodex** [sdsykes/fastimage#31]
When passing a `Pathname` to `FastImage#size` (which responds to :read), if the image dimensions are not found within the first 256 bytes (`LocalFileChunkSize`), the library falls into an infinite loop.
e.g. `width, height = FastImage.size(Rails.root.join('test.jpg'))`

The offending code is in `FastImage#fetch_using_read`, namely:
`while str = readable.read(LocalFileChunkSize)`

`Pathname#read` will repeatedly return the first 256 bytes unless it is open first (such is the case if you typecast to a string beforehand).

I suspect this will affect other classes that respond to `:read` and behave in the same way as `IO.read`

Example image which exhibits this behaviour: https://puu.sh/9pOAv/e0b4e166bd.jpg

**Comment by brendon** [comment]
Hi there, I think I'm still having trouble with this in `2.1.0`. For certain images (and I am using `Pathname` the process just loops infinitely. I've attached one of the files that is affected in case it's something to do with that file. I tried typecasting the `Pathname`'s to strings and everything works fine.
![bron](https://user-images.githubusercontent.com/81871/29493648-72f22d6a-85ee-11e7-8772-9463bab9cc09.JPG)

**Comment by sdsykes** [comment]
I tested with the file you gave, I saved it as a.jpg:

    irb(main):002:0> FastImage.size(Pathname.new("a.jpg"))
    => [800, 600]
    irb(main):003:0>

How can I reproduce this issue?

**Comment by brendon** [comment]
Good question! :) It's definitely `Pathname` related since calling `to_s` on the object works without a hitch, so perhaps there's something going on in the reading. I'm using Ruby 2.3.3 currently.

I'll have a think about it, but if you have any ideas let me know :) I'll check out this repo and run the tests locally and see what happens there.

**Comment by brendon** [comment]
The tests run fine locally. I even tried substituting the `bad.jpg` for a couple of the images that were hanging and it still worked. Super strange. I'll keep looking.

**Comment by brendon** [comment]
Ah! figured it out. I'm decorating the `Pathname` object so its class isn't `Pathname` anymore. I'll move to use another decorator implementation for extending `Pathname` but do you think there's another way to sniff for this type of `read` method without involving `Pathname` directly?

**Comment by sdsykes** [comment]
It seems the arity or IO#read and Pathname#read are the same (-1).
Any other ideas?

**Comment by brendon** [comment]
Yes, I had a look into that too. I guess the only real way is to compare the return value of the first two chunks and if they're identical, its likely to be a pathname, but even then maybe not? Can `IO.read` behave like Pathname by configuration?

**Comment by sdsykes** [comment]
Perhaps define is_a? on your decorator?

    class D
      attr_accessor :thing
      def method_missing(meth, *args)
        thing.send(meth, *args)
      end
    end
    
    d = D.new
    => #<D:0x007f86760599a8>
    d.thing = Pathname.new("a.jpg")
    => #<Pathname:a.jpg>
    d.lstat
    => #<File::Stat dev=0x1000004, ino=31089408, ...>
    d.is_a?(Pathname)
    => false
    
    class D
      def is_a?(klass)
        thing.is_a?(klass)
      end
    end
    
    d.is_a?(Pathname)
    => true

**Comment by brendon** [comment]
That's an interesting approach. Using `SimpleDelegator` I could probably have also just called super in the local `is_a?` method call for the same effect.

In the end I turned my class into a module and just extended the `Pathname` instance with the module's methods. They're short lived objects anyway :)

Thanks for your help with this. Hopefully it'll help others who try something similar! :D
