### ISSUE TITLE
FastImage does not respect EXIF orientation

### ISSUE THREAD

**Issue by chrispine** [sdsykes/fastimage#37]
I would love to use FastImage, because it's so much faster on one core than ImageMagick's `identify` is on eight! However, it gives incorrect results for some images. For example:

http://pine-fm.s3.amazonaws.com/gen_thumbnail/2008.06.17.15.46.54.jpg

```
$ ruby -e "require 'fastimage'; p FastImage.size('gen_thumbnail/2008.06.17.15.46.54.jpg')"
[445, 334]

$ ruby -e "p `identify -format \"%w %h\" gen_thumbnail/2008.06.17.15.46.54.jpg`"
"334 445"
```

`exiftool` also agrees with `identify`.

Note that different programs handle this image differently: Windows preview shows it correctly, OS X preview shows it wrong; Chrome shows it correctly in an `img` tag, but wrong if open directly as a file; IE shows it correctly when opened as a file and in an `img` tag, etc.

Still, I believe the right thing to do is to report the same value that `identify` and `exiftool` do, by respecting the `Orientation` value.

**Comment by aried3r** [comment]
> I would consider exposing the orientation information in the FastImage API somehow if needed.

I'd love to have that! Should I open a separate issue?

**Comment by sdsykes** [comment]
Yes.
