### ISSUE TITLE
FastImage can't determine size or type when getting a StringIO

### ISSUE THREAD

**Issue by phacops** [sdsykes/fastimage#38]
When I pass a `StringIO` to `FastImage.size`, it returns an `UnknownFileType` exception. When passing a `File`, `FastImage` behaves properly.

**Comment by jcward** [comment]
FYI, worked for me:

```
data = File.read("/path/to/image.png")
FastImage.size(StringIO.new(data))
```

Returns proper size, `[744, 163]`
