### ISSUE TITLE
FastImage.size returns nil for valid jpg images

### ISSUE THREAD

**Issue by amitsaxena** [sdsykes/fastimage#42]
1.9.3-p392 :044 > FastImage.size("http://www.inc.com/uploaded_files/image/pan_UnicornClub_31990.jpg")
 => nil 
1.9.3-p392 :045 > FastImage.size("http://www.inc.com/uploaded_files/image/pan_UnicornClub_31990.jpg", :raise_on_failure=>true)
FastImage::UnknownImageType: FastImage::UnknownImageType
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/fastimage-1.6.3/lib/fastimage.rb:190:in `rescue in initialize'
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/fastimage-1.6.3/lib/fastimage.rb:160:in`initialize'
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/fastimage-1.6.3/lib/fastimage.rb:114:in `new'
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/fastimage-1.6.3/lib/fastimage.rb:114:in`size'
    from (irb):45
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.19/lib/rails/commands/console.rb:47:in `start'
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.19/lib/rails/commands/console.rb:8:in`start'
    from /home/amit/.rvm/gems/ruby-1.9.3-p392/gems/railties-3.2.19/lib/rails/commands.rb:41:in `<top (required)>'
    from script/rails:6:in`require'
    from script/rails:6:in `<main>'

Quite a few og:image URLs from inc.com exhibit such behaviour for me:
1.9.3-p392 :046 > FastImage.size("http://www.inc.com/uploaded_files/image/inception-still_45146.jpg")
 => nil

**Comment by apraditya** [comment]
How about encoding the URL? 

```
[3] pry(main)> FastImage.size "https://blog.assunnah.web.id/wp-content/uploads/2016/08/Screenshot 2016-08-03 22.40.28.png"
=> nil
```

**Comment by sdsykes** [comment]
I'm not sure - I've a feeling that it's reasonable to expect the gem user to provide a valid encoded url.
