### ISSUE TITLE
svg image size

### ISSUE THREAD

**Issue by khoan** [sdsykes/fastimage#49]
Not even sure if this is remotely possible. Can we (fastimage) get dimension of svg?

**Comment by sdsykes** [comment]
They are xml - I believe they do specify dimensions in the svg tag. So I think it's possible. I don't know all the details though (e.g. are there rotations, resolution, etc). I'd certainly accept a pull req.

**Comment by sdsykes** [comment]
Fixed by f27a0e594346cb219a3cc3f54747960050c5c8e3
