### ISSUE TITLE
Can it return file size too?

### ISSUE THREAD

**Issue by lulalalalistia** [sdsykes/fastimage#51]
I am planning to develop a PR, but want to know what you think of it.

I use Fastimage to validate remote image fetching. It is good for determining both the size and also the type of image. However I often need to validate file size as well. I am guessing this can be done during when Fastimage does the request too. So I won't need to do my own request in order to find it out. Thoughts?

**Comment by sdsykes** [comment]
I think it could be ok. Something like this?

```
diff --git a/lib/fastimage.rb b/lib/fastimage.rb
index 59efd8e..0906833 100644
--- a/lib/fastimage.rb
+++ b/lib/fastimage.rb
@@ -48,7 +48,7 @@ require 'pathname'
 require 'zlib'
 
 class FastImage
-  attr_reader :size, :type
+  attr_reader :size, :type, :content_length
 
   attr_reader :bytes_read
 
@@ -231,6 +231,8 @@ class FastImage
 
       raise ImageFetchFailure unless res.is_a?(Net::HTTPSuccess)
 
+      @content_length = res.content_length
+
       read_fiber = Fiber.new do
         res.read_body do |str|
           Fiber.yield str
```

You'd use it like this:

```
irb(main):007:0> f = FastImage.new("https://www.google.com/images/srpr/logo11w.png")
=> #<FastImage:0x007ff284bbf138 ...
irb(main):008:0> f.size
=> [538, 190]
irb(main):009:0> f.content_length
=> 14022
```

Would need some tests also, plus docs.

**Comment by lulalala** [comment]
Thanks and please check and see if my test/doc are sufficient :)

**Comment by sdsykes** [comment]
It occurred to me that it won't work for chunked responses:

```
irb(main):006:0> FastImage.new("http://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx?0.37788605550304055").size
=> [669, 695]
irb(main):007:0> FastImage.new("http://www.httpwatch.com/httpgallery/chunked/chunkedimage.aspx?0.37788605550304055").content_length
=> nil
```

So the question is, is it still worth adding this feature even though in some cases it will not work?

**Comment by lulalala** [comment]
Yep as for me the majority of times content length would still be there. If nil is returned I would simply allow downloading it first then examine the size. So yeah I still feel it is useful.
