### ISSUE TITLE
A website URL is wrongly considered as an SVG

### ISSUE THREAD

**Issue by ArnoHolo** [sdsykes/fastimage#55]
Hi,

As the gem verifies the two first characters of the file provided by the URL, a website whose HTML begins with the following xml tag is considered as a SVG image. 
```<?xml version="1.0" encoding="utf-8"?>```

Try with this URL : http://www.paperplanes.de/2015/10/6/the-most-important-thing-about-one-on-ones.html 

I suggest we add deeper verifications to prevent this false positive!

Cheers!

**Comment by sdsykes** [comment]
The library will try to identify what kind of image something is, but indeed, not reliably whether it is an image or not.

In this case, is it  causing a problem? I'd be prepared to add some further check if there was a good reason to (or shoot me a PR).

**Comment by jvenezia** [comment]
Same problem with this url : https://mobile.twitter.com/LNizri/status/621678046165266432

Wrongly considered as SVG :/ Any idea why?

Thanks!

**Comment by sdsykes** [comment]
Well.. it's not an image. It's a web page.

At present FastImage does assume the thing you are passing in is one of the things it can detect.

But if this is a common case, then I'd be happy to accept a change to do better detection of SVG against other kinds of xml files.

**Comment by jvenezia** [comment]
Yep it's just to report the problem :)

I use fastimage to check if the url is an image, but I know it's not the main concern of this gem and I understand this.

I'll check if I can improve this.
