### ISSUE TITLE
Fastimage for Node.js

### ISSUE THREAD

**Issue by ShogunPanda** [sdsykes/fastimage#59]
Hi!
Since I noticed you mention fastimage implementations in other languages, let me share my implementation for Node.js: https://github.com/ShogunPanda/fastimage

Needless to say, your gem was the core inspiration! :)
Thanks!
  Paolo

**Comment by sdsykes** [comment]
Nice!

I'll add it to the list.

**Comment by sdsykes** [comment]
Fixed by 5c64fc9
