### ISSUE TITLE
Expose the orientation information through the fastimage API

### ISSUE THREAD

**Issue by aried3r** [sdsykes/fastimage#61]
Would be useful to conditionally rotate images, since `convert` seems to re-encode the image using `-auto-orient`, even though it's correctly rotated.

**Comment by sdsykes** [comment]
Do you need the full exif orientation value (so a number 1-8)?

**Comment by aried3r** [comment]
What are the alternatives?

**Comment by sdsykes** [comment]
Internally FastImage just needs to know whether the image is rotated in such a way that the height and width are swapped. So it ignores 180 degree rotation, and also flips around either axis.

**Comment by aried3r** [comment]
I'd love to have 1-8 so I can rotate, flip, etc accordingly. :)

**Comment by aried3r** [comment]
Would this be as easy as exposing `@orientation`?

**Comment by sdsykes** [comment]
Yes probably not very hard to do. You have a PR?..  or else I can try to get to it during the weekend.

**Comment by aried3r** [comment]
I don't have a PR ready, only tried to read a bit into the codebase. I'd
welcome it if you find the time!

**Comment by aried3r** [comment]
Thanks, looking good! :) (fixed in https://github.com/sdsykes/fastimage/commit/f3ee9eeace67dd22724062bfbaa22cb4272b79e4 for all those who come across this issue)

About the change in dependencies for addressable, how long are you planning to support Ruby 1.8.7 (or even 1.x) since they all reached their EOL?
