### ISSUE TITLE
Getting the response as nil 

### ISSUE THREAD

**Issue by HimanthTag** [sdsykes/fastimage#63]
Hi All

I am using this gem for quite some time, strangely i started getting an issue with this. I could not get the type or size for this particular image url http://mediaus.topshop.com/wcsstore/TopShopUS/images/catalog/24C02JBLK_normal.jpg

Please help. Thanks in advance

**Comment by sdsykes** [comment]
I guess they are blocking the ruby user agent. You can fix it by setting a different user agent:

FastImage.size("http://mediaus.topshop.com/wcsstore/TopShopUS/images/catalog/24C02JBLK_normal.jpg", :http_header => {'User-Agent' => 'Fake Browser'})
=> [280, 420]

**Comment by sdsykes** [comment]
No further feedback, closing.

**Comment by HimanthTag** [comment]
Sorry, i was away for few days. I tried with setting the fake browser, but still the same nil response.

Am i getting nil because of gem version? And the 280, 420 is the response you got on executing that command line right?

**Comment by sdsykes** [comment]
Using fastimage 1.9.0 

    $ irb
    irb(main):001:0> require 'fastimage'
    => true
    irb(main):002:0> FastImage.size("http://mediaus.topshop.com/wcsstore/TopShopUS/images/catalog/24C02JBLK_normal.jpg", :http_header => {'User-Agent' => 'Fake Browser'})
    => [280, 420]
    irb(main):003:0>

**Comment by sdsykes** [comment]
Make sure your fastimage gem is up to date - then let me know if you still have problems (tell be what ruby version also)
