### ISSUE TITLE
Deprecate Ruby 1.x

### ISSUE THREAD

**Issue by aried3r** [sdsykes/fastimage#65]
Maybe it's time for a fastimage v2 that can drop support for these so addressable can be kept up to date (even though I'd favor #45 to be resolved, as I don't use any of the HTTP stuff either).

What do you think?

**Comment by sdsykes** [comment]
Yes, maybe you are right. I mainly keep 1.8.7 support as there is a project I work on sometimes that uses it. But I think it would be acceptable to drop the support and make a 2.0 release.
