### ISSUE TITLE
 FastImage.size and FastImage.type return nil for certain jpg images

### ISSUE THREAD

**Issue by amitsaxena** [sdsykes/fastimage#71]
Below are a few examples:

`FastImage.size("http://industrym.com/newsite/wp-content/uploads/2016/06/teenage-mutant-ninja-turtles-2.jpg")`

`FastImage.size("http://industrym.com/newsite/wp-content/uploads/2016/06/Crazy-Taco-112.jpg")`

**Comment by sdsykes** [comment]
I cannot see those images, I am getting an error page "Sucuri WebSite Firewall - CloudProxy - Access Denied"

**Comment by amitsaxena** [comment]
The images open up fine for me. Strange! The same image which opens fine on my browser, results in a nil response when I try it with FastImage locally. Anything else that might help debug?

amit@amit:/tmp$ wget "http://industrym.com/newsite/wp-content/uploads/2016/06/teenage-mutant-ninja-turtles-2.jpg"
--2016-07-17 00:48:24--  http://industrym.com/newsite/wp-content/uploads/2016/06/teenage-mutant-ninja-turtles-2.jpg
Resolving industrym.com (industrym.com)... 192.124.249.2
Connecting to industrym.com (industrym.com)|192.124.249.2|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 179886 (176K) [image/jpeg]
Saving to: ‘teenage-mutant-ninja-turtles-2.jpg’

100%[============================================================================================================>] 1,79,886    13.7KB/s   in 12s    

2016-07-17 00:48:38 (14.4 KB/s) - ‘teenage-mutant-ninja-turtles-2.jpg’ saved [179886/179886]

**Comment by sdsykes** [comment]
It probably doesn't like the Ruby user agent.

Try something like this:

    FastImage.size("http://industrym.com/newsite/wp-content/uploads/2016/06/teenage-mutant-ninja-turtles-2.jpg", :http_header => {'User-Agent' => 'Wget/1.11.4'})

**Comment by amitsaxena** [comment]
Ahhh! My Bad!

Thanks for the help, and thank you for the awesome gem!!! :trophy: :trophy: :trophy:
