### ISSUE TITLE
Support for Data URI scheme

### ISSUE THREAD

**Issue by jschwindt** [sdsykes/fastimage#74]
[MetaInspector Gem](https://github.com/jaimeiniesta/metainspector) uses Fastimage and we found that it would be useful to support the [Data URI scheme](https://en.wikipedia.org/wiki/Data_URI_scheme). Looking at the code I think it would be quite easy to convert the base64 data into a StringIO so the rest of the code would work the same way as today.

If there is any chance of adding support for it then I can provide a PR, what do you think?

**Comment by sdsykes** [comment]
Merged.
