### ISSUE TITLE
Size of SVG returning nil

### ISSUE THREAD

**Issue by Jbern16** [sdsykes/fastimage#76]
When try to size a SVG that is returned from a form as a Ruby File, I receive nil. If local sizing of svg's are not supported, documentation needs to be updated.

Example image below: 

[Logo-Bw.svg.zip](https://github.com/sdsykes/fastimage/files/717865/Logo-Bw.svg.zip)

**Comment by sdsykes** [comment]
That svg does not contain a width or height. It does however contain a viewbox. I'm thinking that we should probably recognise the vewbox width and height as the width and height if they are not otherwise set. Here is a similar issue: https://github.com/Hiswe/gulp-svg-symbols/issues/10
