### ISSUE TITLE
content_length always return nil when open a local file

### ISSUE THREAD

**Issue by li-thy-um** [sdsykes/fastimage#77]
when I say: 

```ruby

FastImage.new('/Users/lithium/image.jpg').content_length
```

I expect it returns the content_length of the image file. But it returns `nil`.

Then I read the source code. I found that the method `fetch_using_read` doesn't set the `@content_length`.

Is this a feature? Can we set `@content_length` in `fetch_using_read` to make a consistent interface?

**Comment by sdsykes** [comment]
I think it would be reasonable to set it. I'll see if it's easy to do.
