### ISSUE TITLE
fastimage doesn't support redirects with protocol relative urls

### ISSUE THREAD

**Issue by dennyac** [sdsykes/fastimage#79]
Currently fastimage doesn't support redirects with protocol relative urls. According to the first answer and the comments in this [post](http://stackoverflow.com/questions/9646407/two-forward-slashes-in-a-url-src-href-attribute), it seems like protocol relative urls is an accepted standard. Steps to repro the issue - 

```
2.2.1 :001 > require 'fastimage'
 => true
2.2.1 :002 > url = "https://play.vidyard.com/osHCgNMQPWmwNCzcaVmnfW.jpg"
 => "https://play.vidyard.com/osHCgNMQPWmwNCzcaVmnfW.jpg"
2.2.1 :003 > FastImage.type(url)
 => nil
```

I've raised a PR #78 which has more information and handles protocol relative urls. Hope you find it useful. I'm open to suggestions as well. Thanks!

**Comment by sdsykes** [comment]
Merged.
