### ISSUE TITLE
Hiya this does not seem to work on Google Hosted image

### ISSUE THREAD

**Issue by iwarner** [sdsykes/fastimage#81]
Test URL

https://lh6.googleusercontent.com/5acQZwWMWRJ_D1gHDLa6hw_MMdOGC-lMe_1a6-AsTeP5UaZBM5aiDuQBrpKJIszQnGKYV5nwXk-7L2sea0I-NzEfciN2GKPB64QoyL4Zhi1hQQWLOrp965ug9Alm-vWSnjD3AUW3

Simply returns blank

thanks

**Comment by sdsykes** [comment]
Seems ok to me. Sometimes we have seen problems where you need to set the user agent for the image to be fetched, like FastImage.size("....", :http_header => {'User-Agent' => 'Fake Browser'}), but at least I didn't need to do that.

```
irb(main):001:0> require 'fastimage'
/Library/Ruby/Gems/2.0.0/gems/fastimage-2.1.0/lib/fastimage.rb:67: warning: already initialized constant URI::DEFAULT_PARSER
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/uri/common.rb:545: warning: previous definition of DEFAULT_PARSER was here
=> true
irb(main):002:0> FastImage.size("https://lh6.googleusercontent.com/5acQZwWMWRJ_D1gHDLa6hw_MMdOGC-lMe_1a6-AsTeP5UaZBM5aiDuQBrpKJIszQnGKYV5nwXk-7L2sea0I-NzEfciN2GKPB64QoyL4Zhi1hQQWLOrp965ug9Alm-vWSnjD3AUW3")
=> [750, 422]
irb(main):003:0> FastImage.type("https://lh6.googleusercontent.com/5acQZwWMWRJ_D1gHDLa6hw_MMdOGC-lMe_1a6-AsTeP5UaZBM5aiDuQBrpKJIszQnGKYV5nwXk-7L2sea0I-NzEfciN2GKPB64QoyL4Zhi1hQQWLOrp965ug9Alm-vWSnjD3AUW3")
=> :jpeg
```

**Comment by iwarner** [comment]
Umm I had it inline in a script and it putted nothing ? Tested with other images and it was fine. Maybe I hit some other limitiations with fetching the image. Will test some more.

**Comment by sdsykes** [comment]
Closing, no further feedback.
