### ISSUE TITLE
fastimage android version

### ISSUE THREAD

**Issue by qstumn** [sdsykes/fastimage#84]
https://github.com/qstumn/FastImageSize
I write an android version according to your ideas
But my english is too bad  so i can't provide the English version README  
sorry

**Comment by sdsykes** [comment]
Great, thank you! I'll add a link - I guess it's clear how to use it from the examples anyway (or someone can use google translate).

**Comment by sdsykes** [comment]
Added in 53624694848ffcecdbd37a5733d78eb00ae464c7
