### ISSUE TITLE
ruby interpreter warnings

### ISSUE THREAD

**Issue by dcorrigan** [sdsykes/fastimage#85]
First, thanks for your work on this gem! It's incredibly useful.

It's a very small thing, but I notice that the Ruby interpreter raises warnings in verbose mode for some of the instance variable checks (and a few other things) in fastimage. Would you be interested in a small PR to clean up those warnings? [This line](https://github.com/sdsykes/fastimage/blob/master/lib/fastimage.rb#L382) throws a warning, for example, if `@type` is not previously defined. I don't know if some conditionals are written like that for performance reasons, so disregard this if so.

**Comment by sdsykes** [comment]
Sure, I'll accept a PR, they are unintentional.

**Comment by sdsykes** [comment]
Fixed by bb4e64a455349778af08ca82fdfc3487fb2fc630, thanks
