### ISSUE TITLE
Using fastimage via command-line

### ISSUE THREAD

**Issue by ritiek** [sdsykes/fastimage#94]
Hi and thanks for building fastimage.

I don't see any way to use fastimage from the command-line. Could this feature be added? It will be useful to people who do not know ruby like me. :wink:

**Comment by sdsykes** [comment]
Using it from the command line is possible like so:

    $ ruby -rfastimage -e 'p FastImage.size(ARGV[0])' "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Brown_Flax_Seeds.jpg/1200px-Brown_Flax_Seeds.jpg"
    [1200, 800]
    $

Also you could make a program like so:

    #! /usr/bin/env ruby
    require 'fastimage'
    p FastImage.size(ARGV[1])

So if you put that in a file called fi

    $ cat fi
    #! /usr/bin/env ruby
    require 'fastimage'
    p FastImage.size(ARGV[1])
    $ chmod +x fi
    $ ./fi "https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Brown_Flax_Seeds.jpg/1200px-Brown_Flax_Seeds.jpg"
    [1200, 800]
    $

**Comment by ritiek** [comment]
Having a simple script is very helpful indeed. Thanks again!
