### ISSUE TITLE
Broken on redirected URLs that need encoding.

### ISSUE THREAD

**Issue by wittawasw** [sdsykes/fastimage#95]
I have this one specific problem when using FastImage recently and want some thought on this.

Whenever user try to use URL that need encoding, e.g. some URLs that come with spaces.
I could try encoding it first but if those links are redirected urls and when it's being redirected inside FastImage it would fail with error from `URI.parse` because those redirected URLs is also come with spaces.

The use case that I encounter this particular problem is when user submit `http://` protocol URLs and it's being redirected to `https://` with the spaces in URL that's not being encoded.

As of now, my solution is to implement redirect logic and encode it on my own before using FastImage. I thought that this could be a nice addition to implement on FastImage itself but the thought that this will further exhaust FastImage general performance stop me from doing this. Do you think this is worth doing? I can make a PR.

**Comment by sdsykes** [comment]
I'm not sure I understand this exactly - my understanding is that a url with spaces in must have them encoded otherwise it's not a valid url. 

So if you are seeing a redirect to "https://example.org/foo bar" then that's something that is invalid and we wouldn't particularly want to make a special case for it unless it's commonly happening.

**Comment by wittawasw** [comment]
I think you understand it correctly, at least most of it.
For clarification and future reference, it goes like this.
* User input `http://example.com/foo bar.jpg`
* System notice space in URL, `URI.encode` it to `http://example.com/foo%20bar.jpg`.
* `FastImage.new` with encoded URL.
* The encoded URL got redirected inside `FastImage` to `https://example.com/foo bar.jpg` and got `URI.parse` error due to having space again.

Opinions in my team are divided but I thought this is a particular problem to only specific use case, too. Please feel free to close this issue.

**Comment by sdsykes** [comment]
So, here's a made up test:

    $ curl -i "http://libpixel.com/test/hills%20foo.jpg"
    HTTP/1.1 301 Moved Permanently
    Server: CloudFront
    Date: Thu, 05 Oct 2017 07:29:27 GMT
    Content-Type: text/html
    Content-Length: 183
    Connection: keep-alive
    Location: https://libpixel.com/test/hills%20foo.jpg
    X-Cache: Redirect from cloudfront

As you can see the %20 is preserved in the URL in this case. In your case, is the %20 not being preserved in the redirect (which would not be our fault)? 

Or if it is being preserved, then that would be a bug we need to fix in FastImage.

**Comment by wittawasw** [comment]
I see another point now, this is probably from HTTP spec itself or just their web server specification.
I try calling the URL in question with `curl` and it return with `302` status code.

```
curl -I http://example.com/72cc7b80-66c3-474d-b6ca-1fc4b209ea42/resized/Whispering%20Palms%2010112-46.jpg

HTTP/1.1 302 Redirect
Content-Length: 253
Content-Type: text/html; charset=UTF-8
Location: https://example.com/72cc7b80-66c3-474d-b6ca-1fc4b209ea42/resized/Whispering Palms 10112-46.jpg
Server: Microsoft-IIS/8.0
X-Powered-By: ASP.NET
X-Powered-By-Plesk: PleskWin
Date: Thu, 05 Oct 2017 08:12:01 GMT
```

If I use the URL with 301 permanent redirect in cloudfront just like you,  FastImage or in this case redirection within `Net::HTTP` will preserve encoding. But not with this 302 redirection that I encounter.

**Comment by sdsykes** [comment]
I suppose that's a misconfigured IIS, a URI-reference can't have unencoded spaces in it as I read the spec.

I suppose FastImage could detect and handle this, but my feeling is it's not worth trying to handle errors that are outside of our control.

So my suggestion is you handle the broken redirect first. Unless, that is, it's a common case with IIS servers, but I don't immediately find any discussion of it by googling.

**Comment by wittawasw** [comment]
Yes, I agree with you.
I'm gonna close this issue now, this discussion has come long enough.
Appreciate your participation.
