### ISSUE TITLE
Enable extraction of EXIF from FastImage object

### ISSUE THREAD

**Issue by bermannoah** [sdsykes/fastimage#96]
Hi there --

I'm trying to retrieve the basic dimensions from an image file using as few bytes as humanly possible, then feeding those bytes into fastimage. Unfortunately, when I do this it seems to be unable to find the size of the file, despite those properties existing in the FastImage object. The image is a jpeg and while fastimage can detect the filetype, it struggles with detecting the size...although:

```
 @exif=#<FastImage::Exif:0x007f93cfe6abf8 @height=2832, @long="V", @orientation=1,
# @short="v", @start_byte=6, @stream=#<StringIO:0x007f93cfe6acc0>, @width=4256>,
```

I attempted to use FastImage::Exif.new, but it doesn't seem to be able to read from the stream. Is there a way of giving the user access to just the exif data itself, that's already been read? 

I'm happy to take a look at this this weekend and see if I can come up with a solution (maybe it's as simple as adding an attr_reader? Maybe I'm being extraordinarily dense and missing something? Very possible. 😄 ). Let me know what you think.

**Comment by sdsykes** [comment]
For jpegs the exif data is only used to find the orientation of the image. The width and height are taken from the native data.

So if you provide enough bytes it will be able to return the correct info.

I don't wish to complicate the api by adding the feature of reading the exif size for jpeg files unless many people want it, but indeed you could fork and make the mod for your own use.

**Comment by sdsykes** [comment]
No further feedback, closing.
