### ISSUE TITLE
Name Too Long using base64 image

### ISSUE THREAD

**Issue by fauzieuy** [sdsykes/fastimage#97]
Hi, I found an issue using base64 image from android, I have an api for check size of image from android front end using fastimage, image format using base64,
```
FastImage.new(params[:image]).content_length
```

Here is the relevant part of the stacktrace:
```
Errno::ENAMETOOLONG: File name too long @ rb_sysopen data:image/jpeg;base64 .......
....
from /home/myuser/.rvm/gems/ruby-2.2.3@alo/gems/fastimage-2.0.1/lib/fastimage.rb:337:in `initialize'
```

**Comment by sdsykes** [comment]
Is there something other than "data:" at the beginning of params[:image] ?

If it doesn't start with "data:" then it will attempt to open the string as a file.

**Comment by sdsykes** [comment]
Closing, please reopen with demo string if the problem persists.
